@startuml
start
-> RGB Image;
:Undistort image;
fork
    -> from HLS image format;
    :L channel extraction;
    :Threshold binarization;
fork again
    :S channel extraction;
    :Threshold binarization;
end fork
-> Stacking into a 3D image;
:Perspective Transform;

end
@enduml
